
@----------------------------------------------------------@
|        PLINK!       |     v1.07      |   10/Aug/2009     |
|----------------------------------------------------------|
|  (C) 2009 Shaun Purcell, GNU General Public License, v2  |
|----------------------------------------------------------|
|  For documentation, citation & bug-report instructions:  |
|        http://pngu.mgh.harvard.edu/purcell/plink/        |
@----------------------------------------------------------@

Skipping web check... [ --noweb ] 
Writing this text to log file [ APOC3.log ]
Analysis started: Fri Mar 27 14:03:13 2015

Options in effect:
	--bfile APOC3_1Mb
	--ld rs964184 rs66505542
	--noweb
	--out APOC3

Reading map (extended format) from [ APOC3_1Mb.bim ] 
40644 markers to be included from [ APOC3_1Mb.bim ]
Reading pedigree information from [ APOC3_1Mb.fam ] 
3621 individuals read from [ APOC3_1Mb.fam ] 
0 individuals with nonmissing phenotypes
Assuming a disease phenotype (1=unaff, 2=aff, 0=miss)
Missing phenotype value is also -9
0 cases, 0 controls and 3621 missing
0 males, 0 females, and 3621 of unspecified sex
Warning, found 3621 individuals with ambiguous sex codes
These individuals will be set to missing ( or use --allow-no-sex )
Writing list of these individuals to [ APOC3.nosex ]
Reading genotype bitfile from [ APOC3_1Mb.bed ] 
Detected that binary PED file is v1.00 SNP-major mode
Before frequency and genotyping pruning, there are 40644 SNPs
3621 founders and 0 non-founders found
Total genotyping rate in remaining individuals is 1
0 SNPs failed missingness test ( GENO > 1 )
0 SNPs failed frequency test ( MAF < 0 )
After frequency and genotyping pruning, there are 40644 SNPs
After filtering, 0 cases, 0 controls and 3621 missing
After filtering, 0 males, 0 females, and 3621 of unspecified sex

LD information for SNP pair [ rs964184 rs66505542 ]

   R-sq = 0.902     D' = 0.978

   Haplotype     Frequency    Expectation under LE
   ---------     ---------    --------------------
       GTA          0.130            0.018
       CTA          0.009            0.121
       GT          0.003            0.114
       CT          0.858            0.746

   In phase alleles are GTA/CT

Analysis finished: Fri Mar 27 14:03:18 2015

